"""Update device model with new fields

Revision ID: 3484f76e8eff
Revises: 98db0262d18e
Create Date: 2025-04-29 09:41:24.982412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3484f76e8eff'
down_revision: Union[str, None] = '98db0262d18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.String(), nullable=False))
    op.add_column('devices', sa.Column('last_synced', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('sync_status', sa.Enum('SYNCED', 'CHANGED', 'ERROR', name='devicestatus'), nullable=True))
    op.add_column('devices', sa.Column('sync_enabled', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('terminal_configured', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('theme_configured', sa.Boolean(), nullable=True))
    op.drop_column('devices', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'theme_configured')
    op.drop_column('devices', 'terminal_configured')
    op.drop_column('devices', 'sync_enabled')
    op.drop_column('devices', 'sync_status')
    op.drop_column('devices', 'last_synced')
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###
